name: CI pipeline for SCAS frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository !!!
        uses: actions/checkout@v3

      - name: Log in to DockerHub !!!
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image !!!
        env:
          NAME: ${{ secrets.DOCKERHUB_USERNAME }}
          REPO: scas-frontend
          TAG: ${{ github.sha }}
        run: |
          docker build --no-cache -t $NAME/$REPO:$TAG .
          docker push $NAME/$REPO:$TAG

      # push argocd manifest repo to new tag: https://github.com/leeejjju/scas-manifests.git
      - name: Checkout manifest repository
        uses: actions/checkout@v3
        with:
          repository: leeejjju/scas-manifests
          token: ${{ secrets.GH_TOKEN }}
          path: manifests

      - name: Update image tag in deployment.yaml
        run: |
          cd manifests/apps/frontend
          sed -i "s|image: .*|image: leeejjju/scas-frontend:${{ github.sha }}|" deployment.yaml
          cat deployment.yaml

      - name: Commit and push changes
        run: |
          cd manifests
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "CICD) Update new image tag to ${{ github.sha }}"
          git push origin main

